repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 24.8.0
    hooks: # With 119 line length
    -   id: black
        args: [--line-length=119]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
    -    id: ruff

