name: Validate styles (PR)

on:
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: python -m pip install -Ur requirements.txt
      - name: Run unit tests
        run: python -m unittest discover tests
